name: Build Vue
on: [ push ]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
      - uses: actions/checkout@v3

      - name: Copy config
        uses: mobiledevops/secret-to-file-action@v1
        with:
          base64-encoded-secret: ${{ secrets.CONFIG }}
          filename: 'src/config.ts'
          is-executable: true

      - id: Build-Vue
        uses: xRealNeon/VuePagesAction@1.0.1
        with:
          username: 'NotGeri'
          reponame: 'Predefineds'
          token: ${{ secrets.GITHUB_TOKEN }}
